// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTE6WXmwlXJxCMhJXmYDGsvkPYbuiLxA',
    appId: '1:461314866481:web:bec14412a9a8123a66c410',
    messagingSenderId: '461314866481',
    projectId: 'terakoya-intro-site',
    authDomain: 'terakoya-intro-site.firebaseapp.com',
    storageBucket: 'terakoya-intro-site.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmT2IAVIyxeWFkh0EAR__yXWE2Y26pHa4',
    appId: '1:461314866481:android:8f3b54fee29fceab66c410',
    messagingSenderId: '461314866481',
    projectId: 'terakoya-intro-site',
    storageBucket: 'terakoya-intro-site.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZEKB-wIyolj4BBovu4tXKfjm_RPy-FNU',
    appId: '1:461314866481:ios:49ab97d483f0149b66c410',
    messagingSenderId: '461314866481',
    projectId: 'terakoya-intro-site',
    storageBucket: 'terakoya-intro-site.appspot.com',
    iosClientId: '461314866481-1662gqpe588e8sijshsjv6gdnmht09h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.terakoyaStaffIntroSite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZEKB-wIyolj4BBovu4tXKfjm_RPy-FNU',
    appId: '1:461314866481:ios:49ab97d483f0149b66c410',
    messagingSenderId: '461314866481',
    projectId: 'terakoya-intro-site',
    storageBucket: 'terakoya-intro-site.appspot.com',
    iosClientId: '461314866481-1662gqpe588e8sijshsjv6gdnmht09h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.terakoyaStaffIntroSite',
  );
}
